spring:
    application:
        name: productsapp
    datasource:
        url: jdbc:mysql://localhost:3306/productdb
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:h2:mem:mydb
#        username: sa
#        password: password
#        driverClassName: org.h2.Driver
        # For File based storage
        #url: jdbc:h2:file:/data/demo
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: true
#        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    h2:
#        console:
#            enabled: true